// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo-ep8-BnK9ygtA0QQxS5FfZ7haa3S2ZA',
    appId: '1:492524927923:web:307dbb8e92cce5a68aa9c6',
    messagingSenderId: '492524927923',
    projectId: 'social-media-app-b5b05',
    authDomain: 'social-media-app-b5b05.firebaseapp.com',
    storageBucket: 'social-media-app-b5b05.firebasestorage.app',
    measurementId: 'G-XXNDFJQ3SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXJ80hwtZ4c9jm8SNGLAu_pgxwmedXLZM',
    appId: '1:492524927923:android:13c6af3d554a06ce8aa9c6',
    messagingSenderId: '492524927923',
    projectId: 'social-media-app-b5b05',
    storageBucket: 'social-media-app-b5b05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlO3ojcGfXX-BR4T0FzIl-mSv9_KDPvCI',
    appId: '1:492524927923:ios:525074a8417394558aa9c6',
    messagingSenderId: '492524927923',
    projectId: 'social-media-app-b5b05',
    storageBucket: 'social-media-app-b5b05.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
